
build:
  verbosity: detailed

clone_depth: 1

install:
  - cmd: git submodule -q update --init

environment:
  matrix:
    # MSVC 2015
    - GENERATOR: Visual Studio 14 2015
      CXXFLAGS: /DGTEST_HAS_TR1_TUPLE=0 /DGTEST_HAS_STD_TUPLE=1
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

    # MSVC 2017 /std:c++14
    - GENERATOR: Visual Studio 15 2017
      CXXFLAGS: /std:c++14 /permissive- /DGTEST_HAS_TR1_TUPLE=0 /DGTEST_HAS_STD_TUPLE=1
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    # MSVC 2017 /std:c++latest
    - GENERATOR: Visual Studio 15 2017
      CXXFLAGS: /std:c++latest /permissive- /DGTEST_HAS_TR1_TUPLE=0 /DGTEST_HAS_STD_TUPLE=1
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    # Clang/LLVM 2015
    - GENERATOR: Visual Studio 14 2015
      CXXFLAGS: /DGTEST_HAS_TR1_TUPLE=0 /DGTEST_HAS_STD_TUPLE=1
      TOOLSET: LLVM-vs2014
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

build_script:
  - mkdir build
  - cd build
  - if "%PLATFORM%" == "x64" set GENERATOR=%GENERATOR% Win64
  - ps: |
      if (Test-Path env:TOOLSET) {
        cmake -G "$env:GENERATOR" -T "$env:TOOLSET" -DMPARK_VARIANT_INCLUDE_TESTS="mpark" ..
      } else {
        cmake -G "$env:GENERATOR" -DMPARK_VARIANT_INCLUDE_TESTS="mpark" ..
      }
  - cmake --build . --config %CONFIGURATION%
  - ctest -V
